"""initial enterprise schema

Revision ID: d58e9143a8d0
Revises:
Create Date: 2026-09-23 22:54:34.963949
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd58e9143a8d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_archives',
    sa.Column('source_event_id', sa.Uuid(), nullable=False),
    sa.Column('event_payload', sa.LargeBinary(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('original_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archive_reference', sa.String(length=500), nullable=False),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('retention_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_archives'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('retention_archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('event_hash', name='uq_audit_event_hash')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_actor', ['actor_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_object', ['object_type', 'object_id', 'occurred_at'], unique=False)

    op.create_table('background_jobs',
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=160), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs')),
    sa.UniqueConstraint('deduplication_key', name='uq_background_job_dedupe')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index('ix_jobs_claim', ['status', 'run_at', 'locked_until'], unique=False)

    op.create_table('business_holidays',
    sa.Column('calendar_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_holidays')),
    sa.UniqueConstraint('calendar_code', 'holiday_date', name='uq_business_holiday_date')
    )
    with op.batch_alter_table('business_holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_holidays_created_at'), ['created_at'], unique=False)

    op.create_table('data_classifications',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('allow_ai', sa.Boolean(), nullable=False),
    sa.Column('allow_export', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_classifications')),
    sa.UniqueConstraint('code', name=op.f('uq_data_classifications_code'))
    )
    with op.batch_alter_table('data_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_classifications_created_at'), ['created_at'], unique=False)

    op.create_table('oidc_transactions',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce_ciphertext', sa.Text(), nullable=False),
    sa.Column('return_path', sa.String(length=255), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_transactions')),
    sa.UniqueConstraint('nonce_hash', name=op.f('uq_oidc_transactions_nonce_hash')),
    sa.UniqueConstraint('state_hash', name=op.f('uq_oidc_transactions_state_hash'))
    )
    with op.batch_alter_table('oidc_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_transactions_created_at'), ['created_at'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_created_at'), ['created_at'], unique=False)

    op.create_table('rate_limit_buckets',
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_buckets')),
    sa.UniqueConstraint('bucket_key', name=op.f('uq_rate_limit_buckets_bucket_key'))
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_created_at'), ['created_at'], unique=False)

    op.create_table('request_field_definitions',
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=40), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('validation_schema', sa.JSON(), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=False),
    sa.Column('visible_roles', sa.JSON(), nullable=False),
    sa.Column('visible_categories', sa.JSON(), nullable=False),
    sa.Column('editable_after_submission', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_field_definitions')),
    sa.UniqueConstraint('field_key', name=op.f('uq_request_field_definitions_field_key'))
    )
    with op.batch_alter_table('request_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_field_definitions_created_at'), ['created_at'], unique=False)

    op.create_table('risk_levels',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_risk_levels_risk_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_levels')),
    sa.UniqueConstraint('code', name=op.f('uq_risk_levels_code'))
    )
    with op.batch_alter_table('risk_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_levels_created_at'), ['created_at'], unique=False)

    op.create_table('roles',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('identity_provider', sa.String(length=80), nullable=True),
    sa.Column('identity_subject', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('job_title', sa.String(length=160), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_break_glass', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_nonnegative')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_users_manager_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('public_id', name=op.f('uq_users_public_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_users_email_active', ['email_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email_normalized'), ['email_normalized'], unique=False)
        batch_op.create_index('ix_users_identity', ['identity_provider', 'identity_subject'], unique=True)

    op.create_table('backup_records',
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('backup_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location_uri', sa.String(length=1000), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=40), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_backup_records_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_records'))
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_records_created_at'), ['created_at'], unique=False)

    op.create_table('delegations',
    sa.Column('delegator_id', sa.Uuid(), nullable=False),
    sa.Column('delegate_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('scope_value', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_delegations_delegation_end_after_start')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_delegations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], name=op.f('fk_delegations_delegate_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], name=op.f('fk_delegations_delegator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delegations'))
    )
    with op.batch_alter_table('delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegations_created_at'), ['created_at'], unique=False)

    op.create_table('email_templates',
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subject_template', sa.String(length=500), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('allowed_variables', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_email_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates')),
    sa.UniqueConstraint('event_key', 'locale', 'version', name='uq_email_template_version')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_templates_event_key'), ['event_key'], unique=False)

    op.create_table('exception_categories',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('default_duration_days', sa.Integer(), nullable=True),
    sa.Column('maximum_duration_days', sa.Integer(), nullable=True),
    sa.Column('risk_level_id', sa.Uuid(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['exception_categories.id'], name=op.f('fk_exception_categories_parent_id_exception_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_level_id'], ['risk_levels.id'], name=op.f('fk_exception_categories_risk_level_id_risk_levels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_exception_categories_code'))
    )
    with op.batch_alter_table('exception_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_categories_created_at'), ['created_at'], unique=False)

    op.create_table('export_records',
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('export_type', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('location_uri', sa.String(length=1000), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_export_records_requested_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_records'))
    )
    with op.batch_alter_table('export_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_records_created_at'), ['created_at'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_idempotency_records_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('actor_id', 'operation', 'idempotency_key', name='uq_idempotency_operation')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_created_at'), ['created_at'], unique=False)

    op.create_table('local_recovery_codes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_from_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_local_recovery_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_recovery_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_local_recovery_codes_code_hash'))
    )
    with op.batch_alter_table('local_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_recovery_codes_created_at'), ['created_at'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_created_at'), ['created_at'], unique=False)

    op.create_table('secret_records',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=512), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_secret_records_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_records')),
    sa.UniqueConstraint('name', name=op.f('uq_secret_records_name'))
    )
    with op.batch_alter_table('secret_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_records_created_at'), ['created_at'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('identity_provider', sa.String(length=80), nullable=False),
    sa.Column('auth_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assurance_level', sa.String(length=160), nullable=True),
    sa.Column('auth_methods', sa.JSON(), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_sessions_user_active', ['user_id', 'revoked_at', 'idle_expires_at'], unique=False)

    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_system_configs_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs')),
    sa.UniqueConstraint('config_key', 'scope', name='uq_system_configs_key_scope')
    )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configs_created_at'), ['created_at'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_user_roles_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_created_at'), ['created_at'], unique=False)

    op.create_table('approval_workflows',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('exception_type', sa.String(length=100), nullable=True),
    sa.Column('risk_level_id', sa.Uuid(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['exception_categories.id'], name=op.f('fk_approval_workflows_category_id_exception_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_approval_workflows_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_level_id'], ['risk_levels.id'], name=op.f('fk_approval_workflows_risk_level_id_risk_levels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_workflows'))
    )
    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_workflows_created_at'), ['created_at'], unique=False)

    op.create_table('approver_groups',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['exception_categories.id'], name=op.f('fk_approver_groups_category_id_exception_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approver_groups')),
    sa.UniqueConstraint('code', name=op.f('uq_approver_groups_code'))
    )
    with op.batch_alter_table('approver_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approver_groups_created_at'), ['created_at'], unique=False)

    op.create_table('approver_group_members',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_backup', sa.Boolean(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['approver_groups.id'], name=op.f('fk_approver_group_members_group_id_approver_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_approver_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approver_group_members')),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_approver_group_member')
    )
    with op.batch_alter_table('approver_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approver_group_members_created_at'), ['created_at'], unique=False)

    op.create_table('exception_requests',
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('exception_type', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('application_name', sa.String(length=200), nullable=False),
    sa.Column('application_service_id', sa.String(length=120), nullable=True),
    sa.Column('application_owner', sa.String(length=200), nullable=True),
    sa.Column('business_owner', sa.String(length=200), nullable=False),
    sa.Column('technology_owner', sa.String(length=200), nullable=False),
    sa.Column('environment', sa.String(length=80), nullable=False),
    sa.Column('asset_system', sa.String(length=240), nullable=False),
    sa.Column('cloud_account', sa.String(length=200), nullable=True),
    sa.Column('data_classification_code', sa.String(length=50), nullable=False),
    sa.Column('information_sensitivity', sa.String(length=120), nullable=True),
    sa.Column('regulatory_impact', sa.Text(), nullable=True),
    sa.Column('control_excepted', sa.String(length=500), nullable=False),
    sa.Column('current_control', sa.Text(), nullable=False),
    sa.Column('requested_exception', sa.Text(), nullable=False),
    sa.Column('reason_control_cannot_follow', sa.Text(), nullable=False),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('security_impact', sa.Text(), nullable=False),
    sa.Column('compensating_controls', sa.Text(), nullable=False),
    sa.Column('remediation_plan', sa.Text(), nullable=False),
    sa.Column('remediation_owner_id', sa.Uuid(), nullable=True),
    sa.Column('remediation_target_date', sa.Date(), nullable=True),
    sa.Column('remediation_status', sa.String(length=40), nullable=False),
    sa.Column('remediation_progress', sa.Integer(), nullable=False),
    sa.Column('remediation_closure_date', sa.Date(), nullable=True),
    sa.Column('requested_start_date', sa.Date(), nullable=False),
    sa.Column('requested_expiry_date', sa.Date(), nullable=False),
    sa.Column('requested_duration_days', sa.Integer(), nullable=False),
    sa.Column('risk_level_id', sa.Uuid(), nullable=False),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage_key', sa.String(length=100), nullable=True),
    sa.Column('original_expiry_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('extension_count', sa.Integer(), nullable=False),
    sa.Column('pending_extension_expiry_date', sa.Date(), nullable=True),
    sa.Column('pending_extension_reason', sa.Text(), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('last_modified_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('requested_expiry_date >= requested_start_date', name=op.f('ck_exception_requests_request_expiry_after_start')),
    sa.CheckConstraint('extension_count >= 0', name=op.f('ck_exception_requests_extension_count_nonnegative')),
    sa.CheckConstraint('version > 0', name=op.f('ck_exception_requests_request_version_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['exception_categories.id'], name=op.f('fk_exception_requests_category_id_exception_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_exception_requests_created_by_id_users')),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], name=op.f('fk_exception_requests_last_modified_by_id_users')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_exception_requests_manager_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remediation_owner_id'], ['users.id'], name=op.f('fk_exception_requests_remediation_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_exception_requests_requester_id_users')),
    sa.ForeignKeyConstraint(['risk_level_id'], ['risk_levels.id'], name=op.f('fk_exception_requests_risk_level_id_risk_levels')),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], name=op.f('fk_exception_requests_workflow_id_approval_workflows'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_requests'))
    )
    with op.batch_alter_table('exception_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_exception_requests_status'), ['status'], unique=False)
        batch_op.create_index('ix_requests_requester_status', ['requester_id', 'status'], unique=False)
        batch_op.create_index('ix_requests_risk_status', ['risk_level_id', 'status'], unique=False)
        batch_op.create_index('ix_requests_status_expiry', ['status', 'expiry_date'], unique=False)

    op.create_table('workflow_stages',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('stage_key', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('sla_business_days', sa.Integer(), nullable=False),
    sa.Column('approver_group_id', sa.Uuid(), nullable=True),
    sa.Column('backup_approver_id', sa.Uuid(), nullable=True),
    sa.Column('minimum_approvals', sa.Integer(), nullable=False),
    sa.Column('maximum_approvals', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_workflow_stages_workflow_stage_sequence_positive')),
    sa.ForeignKeyConstraint(['approver_group_id'], ['approver_groups.id'], name=op.f('fk_workflow_stages_approver_group_id_approver_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['backup_approver_id'], ['users.id'], name=op.f('fk_workflow_stages_backup_approver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], name=op.f('fk_workflow_stages_workflow_id_approval_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stages')),
    sa.UniqueConstraint('workflow_id', 'sequence', name='uq_workflow_stage_sequence')
    )
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_stages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_stages_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('feature', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('deployment_name', sa.String(length=160), nullable=True),
    sa.Column('model_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_token_count', sa.Integer(), nullable=False),
    sa.Column('output_token_count', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('injection_indicators', sa.JSON(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_ai_analyses_request_id_exception_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_ai_analyses_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_ai_request_feature', ['request_id', 'feature', 'created_at'], unique=False)

    op.create_table('approval_assignments',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_stage_id', sa.Uuid(), nullable=True),
    sa.Column('stage_key', sa.String(length=100), nullable=False),
    sa.Column('stage_name', sa.String(length=160), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('delegated_from_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approval_assignments_approver_id_users')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_approval_assignments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delegated_from_id'], ['users.id'], name=op.f('fk_approval_assignments_delegated_from_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_approval_assignments_request_id_exception_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_stage_id'], ['workflow_stages.id'], name=op.f('fk_approval_assignments_workflow_stage_id_workflow_stages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_assignments')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_approval_assignments_token_hash'))
    )
    with op.batch_alter_table('approval_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_assignments_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_approvals_assignee_status', ['approver_id', 'status', 'due_at'], unique=False)
        batch_op.create_index('ix_approvals_request_stage', ['request_id', 'stage_key'], unique=False)

    op.create_table('attachments',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.String(length=30), nullable=False),
    sa.Column('scan_engine', sa.String(length=80), nullable=True),
    sa.Column('scan_engine_version', sa.String(length=80), nullable=True),
    sa.Column('scan_result', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.String(length=80), nullable=True),
    sa.Column('evidence_source', sa.String(length=160), nullable=True),
    sa.Column('provided_by', sa.Uuid(), nullable=True),
    sa.Column('provided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_attachments_attachment_size_positive')),
    sa.ForeignKeyConstraint(['provided_by'], ['users.id'], name=op.f('fk_attachments_provided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_attachments_request_id_exception_requests')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_stored_filename'), ['stored_filename'], unique=False)

    op.create_table('comments',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_clarification_response', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_comments_request_id_exception_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_request_id'), ['request_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_notifications_request_id_exception_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('idempotency_key', name='uq_notification_idempotency_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('request_field_values',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_request_field_values_created_by_id_users')),
    sa.ForeignKeyConstraint(['field_id'], ['request_field_definitions.id'], name=op.f('fk_request_field_values_field_id_request_field_definitions')),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_request_field_values_request_id_exception_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_request_field_values_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_field_values')),
    sa.UniqueConstraint('request_id', 'field_id', name='uq_request_field_value')
    )
    with op.batch_alter_table('request_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_field_values_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_field_values_request_id'), ['request_id'], unique=False)

    op.create_table('ai_historical_references',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('historical_request_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_reason', sa.Text(), nullable=False),
    sa.Column('historical_decision', sa.String(length=40), nullable=True),
    sa.Column('historical_risk_level', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], name=op.f('fk_ai_historical_references_analysis_id_ai_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['historical_request_id'], ['exception_requests.id'], name=op.f('fk_ai_historical_references_historical_request_id_exception_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_historical_references')),
    sa.UniqueConstraint('analysis_id', 'historical_request_id', name='uq_ai_historical_reference')
    )
    with op.batch_alter_table('ai_historical_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_historical_references_created_at'), ['created_at'], unique=False)

    op.create_table('ai_log_findings',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('reason_flagged', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=False),
    sa.Column('recommended_investigation', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_malicious_claim', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], name=op.f('fk_ai_log_findings_analysis_id_ai_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_log_findings'))
    )
    with op.batch_alter_table('ai_log_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_log_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_ai_log_findings_window', ['window_start', 'window_end'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=80), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], name=op.f('fk_ai_recommendations_analysis_id_ai_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_recommendations_created_at'), ['created_at'], unique=False)

    op.create_table('approval_actions',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('delegated_from_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('request_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_actions_actor_id_users')),
    sa.ForeignKeyConstraint(['assignment_id'], ['approval_assignments.id'], name=op.f('fk_approval_actions_assignment_id_approval_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegated_from_id'], ['users.id'], name=op.f('fk_approval_actions_delegated_from_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_approval_actions_request_id_exception_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_actions')),
    sa.UniqueConstraint('idempotency_key', name='uq_approval_action_idempotency')
    )
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_actions_created_at'), ['created_at'], unique=False)

    op.create_table('approval_tokens',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_ip', sa.String(length=64), nullable=True),
    sa.Column('last_used_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['approval_assignments.id'], name=op.f('fk_approval_tokens_assignment_id_approval_assignments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_approval_tokens_token_hash'))
    )
    with op.batch_alter_table('approval_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tokens_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tokens_created_at'), ['created_at'], unique=False)

    op.create_table('remediation_updates',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=False),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evidence_attachment_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_remediation_updates_actor_id_users')),
    sa.ForeignKeyConstraint(['evidence_attachment_id'], ['attachments.id'], name=op.f('fk_remediation_updates_evidence_attachment_id_attachments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['exception_requests.id'], name=op.f('fk_remediation_updates_request_id_exception_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_updates'))
    )
    with op.batch_alter_table('remediation_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remediation_updates_request_id'), ['request_id'], unique=False)

    # Database-level audit immutability. Retention deletion is permitted only inside a
    # transaction that explicitly sets the local maintenance flag.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
        CREATE OR REPLACE FUNCTION reject_audit_mutation()
        RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' AND current_setting('app.audit_retention', true) = 'on' THEN
            RETURN OLD;
          END IF;
          RAISE EXCEPTION 'audit_events is append-only';
        END;
        $$ LANGUAGE plpgsql;
        """)
        op.execute("""
        CREATE TRIGGER audit_events_no_update_delete
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();
        """)
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("""
        CREATE TRIGGER audit_events_no_update
        BEFORE UPDATE ON audit_events
        BEGIN SELECT RAISE(ABORT, 'audit_events is append-only'); END;
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remediation_updates_request_id'))

    op.drop_table('remediation_updates')
    with op.batch_alter_table('approval_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tokens_created_at'))
        batch_op.drop_index(batch_op.f('ix_approval_tokens_assignment_id'))

    op.drop_table('approval_tokens')
    with op.batch_alter_table('approval_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_actions_created_at'))

    op.drop_table('approval_actions')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_created_at'))

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('ai_log_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_log_findings_window')
        batch_op.drop_index(batch_op.f('ix_ai_log_findings_created_at'))

    op.drop_table('ai_log_findings')
    with op.batch_alter_table('ai_historical_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_historical_references_created_at'))

    op.drop_table('ai_historical_references')
    with op.batch_alter_table('request_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_field_values_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_field_values_created_at'))

    op.drop_table('request_field_values')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_request_id'))

    op.drop_table('comments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_stored_filename'))
        batch_op.drop_index(batch_op.f('ix_attachments_sha256'))
        batch_op.drop_index(batch_op.f('ix_attachments_request_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_created_at'))

    op.drop_table('attachments')
    with op.batch_alter_table('approval_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_approvals_request_stage')
        batch_op.drop_index('ix_approvals_assignee_status')
        batch_op.drop_index(batch_op.f('ix_approval_assignments_created_at'))

    op.drop_table('approval_assignments')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_request_feature')
        batch_op.drop_index(batch_op.f('ix_ai_analyses_created_at'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_stages_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_stages_created_at'))

    op.drop_table('workflow_stages')
    with op.batch_alter_table('exception_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_requests_status_expiry')
        batch_op.drop_index('ix_requests_risk_status')
        batch_op.drop_index('ix_requests_requester_status')
        batch_op.drop_index(batch_op.f('ix_exception_requests_status'))
        batch_op.drop_index(batch_op.f('ix_exception_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_exception_requests_created_at'))

    op.drop_table('exception_requests')
    with op.batch_alter_table('approver_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approver_group_members_created_at'))

    op.drop_table('approver_group_members')
    with op.batch_alter_table('approver_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approver_groups_created_at'))

    op.drop_table('approver_groups')
    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_workflows_created_at'))

    op.drop_table('approval_workflows')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_created_at'))

    op.drop_table('user_roles')
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configs_created_at'))

    op.drop_table('system_configs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_sessions_created_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('secret_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_records_created_at'))

    op.drop_table('secret_records')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_created_at'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('local_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_recovery_codes_created_at'))

    op.drop_table('local_recovery_codes')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_created_at'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('export_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_records_created_at'))

    op.drop_table('export_records')
    with op.batch_alter_table('exception_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_categories_created_at'))

    op.drop_table('exception_categories')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_event_key'))
        batch_op.drop_index(batch_op.f('ix_email_templates_created_at'))

    op.drop_table('email_templates')
    with op.batch_alter_table('delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegations_created_at'))

    op.drop_table('delegations')
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_records_created_at'))

    op.drop_table('backup_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_identity')
        batch_op.drop_index(batch_op.f('ix_users_email_normalized'))
        batch_op.drop_index('ix_users_email_active')
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('risk_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_levels_created_at'))

    op.drop_table('risk_levels')
    with op.batch_alter_table('request_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_field_definitions_created_at'))

    op.drop_table('request_field_definitions')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_created_at'))

    op.drop_table('rate_limit_buckets')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_created_at'))

    op.drop_table('permissions')
    with op.batch_alter_table('oidc_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_transactions_created_at'))

    op.drop_table('oidc_transactions')
    with op.batch_alter_table('data_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_classifications_created_at'))

    op.drop_table('data_classifications')
    with op.batch_alter_table('business_holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_holidays_created_at'))

    op.drop_table('business_holidays')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_claim')
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_created_at'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_object')
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))
        batch_op.drop_index('ix_audit_actor')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('audit_events')
    op.drop_table('audit_archives')
    # ### end Alembic commands ###
